### ISSUE TITLE
Not able to run local chain 

### ISSUE THREAD

**Issue by robcxyz** [icon-project/gochain-local#9]
I am getting this error trying to run the compose-single.yml. Submitted PR to update the image as well which is needed to get to this error log.

```
gochain-iconee  | I|20231106-12:25:41.673371|b6b5|-|main|main.go:466   ____  ___   ____ _   _    _    ___ _   _ 
gochain-iconee  | I|20231106-12:25:41.673506|b6b5|-|main|main.go:466  / ___|/ _ \ / ___| | | |  / \  |_ _| \ | |
gochain-iconee  | I|20231106-12:25:41.673526|b6b5|-|main|main.go:466 | |  _| | | | |   | |_| | / _ \  | ||  \| |
gochain-iconee  | I|20231106-12:25:41.673541|b6b5|-|main|main.go:466 | |_| | |_| | |___|  _  |/ ___ \ | || |\  |
gochain-iconee  | I|20231106-12:25:41.673555|b6b5|-|main|main.go:466  \____|\___/ \____|_| |_/_/   \_\___|_| \_|
gochain-iconee  | I|20231106-12:25:41.673571|b6b5|-|main|main.go:468 Version : v1.3.12
gochain-iconee  | I|20231106-12:25:41.673590|b6b5|-|main|main.go:469 Build   : linux/amd64 tags(rocksdb)-2023-11-04-05:39:57
gochain-iconee  | I|20231106-12:25:41.673607|b6b5|-|metric|metric.go:168 Initialize rootMetricCtx
gochain-iconee  | T|20231106-12:25:41.673751|b6b5|-|TP|peerdispatcher.go:81 registerPeerHandler &{0xc0000c1590 0xc000174010 map[] map[] 2 {{0 0} 0 0 0 0} {0 0}} true
gochain-iconee  | T|20231106-12:25:41.673801|b6b5|-|TP|peerdispatcher.go:81 registerPeerHandler &{0xc0000c1650 :8080 map[] {{0 0} 0 0 0 0}} true
gochain-iconee  | I|20231106-12:25:41.674003|b6b5|-|eeproxy|enginefactory.go:9 Allocate Engines:[python java]
gochain-iconee  | D|20231106-12:25:41.682878|b6b5|-|javaee|javaee.go:94 JavaEE Init net(unix), addr(/tmp/socket)
gochain-iconee  | D|20231106-12:25:41.683302|b6b5|-|javaee|javaee.go:72 start JavaEE addr(/tmp/socket), PID(25), state(0x0), 
gochain-iconee  | I|20231106-12:25:41.683448|b6b5|-|pyee|pyee.go:172 start instance uid=214b2a35-8564-47d5-b59c-58df846ef764
gochain-iconee  | I|20231106-12:25:41.684615|b6b5|-|chain|chain.go:466 ConfigFilepath /goloop/data/config.json BaseDir ../chain/iconee ChainDir /goloop/chain/iconee
gochain-iconee  | I|20231106-12:25:41.684697|b6b5|faddbb|chain|chain.go:389 prepare a directory /goloop/chain/iconee/db for database
gochain-iconee  | T|20231106-12:25:41.684974|b6b5|-|db|rocks_db.go:82 fail to rocksdb_list_column_families IO error: No such file or directory: While opening a file for sequentially reading: /goloop/chain/iconee/db/3/CURRENT: No such file or directory
gochain-iconee  | I|20231106-12:25:41.764030|b6b5|faddbb|chain|chain.go:380 STARTING Consensus
gochain-iconee  | I|20231106-12:25:41.764202|b6b5|faddbb|NM|network.go:61 NetworkManager use channel=faddbb for cid=0xfaddbb nid=0x3
gochain-iconee  | I|20231106-12:25:41.764309|b6b5|faddbb|SV|txidcache.go:194 NewTxIDCache: slotDuration=1000000000 slotSize=5000
gochain-iconee  | D|20231106-12:25:41.798667|b6b5|faddbb|BM|manager.go:582 NewBlockManager
gochain-iconee  | D|20231106-12:25:41.815747|b6b5|faddbb|BM|manager.go:878 FinalizeGenesisBlock()
gochain-iconee  | D|20231106-12:25:41.816028|b6b5|faddbb|SV|transition.go:447 reportValidation(err=<nil>)
gochain-iconee  | D|20231106-12:25:41.816320|b6b5|faddbb|SV|transition.go:746 Transition.doExecute: height=0 csi=ConsensusInfo(proposer=<nil>,voters=<nil>,voted=[])
gochain-iconee  | T|20231106-12:25:41.816343|b6b5|faddbb|SV|transition_se.go:38 START TX <0xfaddbb095705302978d83c934a44d24d09ae5ba01466ec3d5ed7493ea2319764>
gochain-iconee  | W|20231106-12:25:41.816766|b6b5|faddbb|SV|transition_se.go:69 Fail to execute transaction err=E2100:FAIL to deploy ChainScore
gochain-iconee  | github.com/icon-project/goloop/common/errors.Code.Wrapf
gochain-iconee  | 	/work/common/errors/errors.go:100
gochain-iconee  | github.com/icon-project/goloop/service/transaction.(*genesisV3).Execute
gochain-iconee  | 	/work/service/transaction/genesis_v3.go:275
gochain-iconee  | github.com/icon-project/goloop/service.(*transition).executeTxsSequential
gochain-iconee  | 	/work/service/transition_se.go:60
gochain-iconee  | github.com/icon-project/goloop/service.(*transition).executeTxs
gochain-iconee  | 	/work/service/transition.go:906
gochain-iconee  | github.com/icon-project/goloop/service.(*transition).doExecute
gochain-iconee  | 	/work/service/transition.go:760
gochain-iconee  | runtime.goexit
gochain-iconee  | 	/usr/local/go/src/runtime/asm_amd64.s:1571
gochain-iconee  | Wrapping E0005:RevisionIsHigherMax(19 > 9)
gochain-iconee  | github.com/icon-project/goloop/common/errors.Code.Errorf
gochain-iconee  | 	/work/common/errors/errors.go:92
gochain-iconee  | github.com/icon-project/goloop/service/platform/basic.(*ChainScore).Install
gochain-iconee  | 	/work/service/platform/basic/chainscore.go:632
gochain-iconee  | github.com/icon-project/goloop/service/contract.DeployAndInstallSystemSCORE
gochain-iconee  | 	/work/service/contract/contractmanager.go:108
gochain-iconee  | github.com/icon-project/goloop/service/transaction.(*genesisV3).Execute
gochain-iconee  | 	/work/service/transaction/genesis_v3.go:273
gochain-iconee  | github.com/icon-project/goloop/service.(*transition).executeTxsSequential
gochain-iconee  | 	/work/service/transition_se.go:60
gochain-iconee  | github.com/icon-project/goloop/service.(*transition).executeTxs
gochain-iconee  | 	/work/service/transition.go:906
gochain-iconee  | github.com/icon-project/goloop/service.(*transition).doExecute
gochain-iconee  | 	/work/service/transition.go:760
gochain-iconee  | runtime.goexit
gochain-iconee  | 	/usr/local/go/src/runtime/asm_amd64.s:1571
gochain-iconee  | D|20231106-12:25:41.816804|b6b5|faddbb|SV|transition.go:472 reportExecution(err=E2100:FAIL to deploy ChainScore
gochain-iconee  | github.com/icon-project/goloop/common/errors.Code.Wrapf
gochain-iconee  | 	/work/common/errors/errors.go:100
gochain-iconee  | github.com/icon-project/goloop/service/transaction.(*genesisV3).Execute
gochain-iconee  | 	/work/service/transaction/genesis_v3.go:275
gochain-iconee  | github.com/icon-project/goloop/service.(*transition).executeTxsSequential
gochain-iconee  | 	/work/service/transition_se.go:60
gochain-iconee  | github.com/icon-project/goloop/service.(*transition).executeTxs
gochain-iconee  | 	/work/service/transition.go:906
gochain-iconee  | github.com/icon-project/goloop/service.(*transition).doExecute
gochain-iconee  | 	/work/service/transition.go:760
gochain-iconee  | runtime.goexit
gochain-iconee  | 	/usr/local/go/src/runtime/asm_amd64.s:1571
gochain-iconee  | Wrapping E0005:RevisionIsHigherMax(19 > 9)
gochain-iconee  | github.com/icon-project/goloop/common/errors.Code.Errorf
gochain-iconee  | 	/work/common/errors/errors.go:92
gochain-iconee  | github.com/icon-project/goloop/service/platform/basic.(*ChainScore).Install
gochain-iconee  | 	/work/service/platform/basic/chainscore.go:632
gochain-iconee  | github.com/icon-project/goloop/service/contract.DeployAndInstallSystemSCORE
gochain-iconee  | 	/work/service/contract/contractmanager.go:108
gochain-iconee  | github.com/icon-project/goloop/service/transaction.(*genesisV3).Execute
gochain-iconee  | 	/work/service/transaction/genesis_v3.go:273
gochain-iconee  | github.com/icon-project/goloop/service.(*transition).executeTxsSequential
gochain-iconee  | 	/work/service/transition_se.go:60
gochain-iconee  | github.com/icon-project/goloop/service.(*transition).executeTxs
gochain-iconee  | 	/work/service/transition.go:906
gochain-iconee  | github.com/icon-project/goloop/service.(*transition).doExecute
gochain-iconee  | 	/work/service/transition.go:760
gochain-iconee  | runtime.goexit
gochain-iconee  | 	/usr/local/go/src/runtime/asm_amd64.s:1571)
gochain-iconee  | T|20231106-12:25:41.816829|b6b5|faddbb|SV|transition.go:477 Execution failed with err=E2100:FAIL to deploy ChainScore
gochain-iconee  | github.com/icon-project/goloop/common/errors.Code.Wrapf
gochain-iconee  | 	/work/common/errors/errors.go:100
gochain-iconee  | github.com/icon-project/goloop/service/transaction.(*genesisV3).Execute
gochain-iconee  | 	/work/service/transaction/genesis_v3.go:275
gochain-iconee  | github.com/icon-project/goloop/service.(*transition).executeTxsSequential
gochain-iconee  | 	/work/service/transition_se.go:60
gochain-iconee  | github.com/icon-project/goloop/service.(*transition).executeTxs
gochain-iconee  | 	/work/service/transition.go:906
gochain-iconee  | github.com/icon-project/goloop/service.(*transition).doExecute
gochain-iconee  | 	/work/service/transition.go:760
gochain-iconee  | runtime.goexit
gochain-iconee  | 	/usr/local/go/src/runtime/asm_amd64.s:1571
gochain-iconee  | Wrapping E0005:RevisionIsHigherMax(19 > 9)
gochain-iconee  | github.com/icon-project/goloop/common/errors.Code.Errorf
gochain-iconee  | 	/work/common/errors/errors.go:92
gochain-iconee  | github.com/icon-project/goloop/service/platform/basic.(*ChainScore).Install
gochain-iconee  | 	/work/service/platform/basic/chainscore.go:632
gochain-iconee  | github.com/icon-project/goloop/service/contract.DeployAndInstallSystemSCORE
gochain-iconee  | 	/work/service/contract/contractmanager.go:108
gochain-iconee  | github.com/icon-project/goloop/service/transaction.(*genesisV3).Execute
gochain-iconee  | 	/work/service/transaction/genesis_v3.go:273
gochain-iconee  | github.com/icon-project/goloop/service.(*transition).executeTxsSequential
gochain-iconee  | 	/work/service/transition_se.go:60
gochain-iconee  | github.com/icon-project/goloop/service.(*transition).executeTxs
gochain-iconee  | 	/work/service/transition.go:906
gochain-iconee  | github.com/icon-project/goloop/service.(*transition).doExecute
gochain-iconee  | 	/work/service/transition.go:760
gochain-iconee  | runtime.goexit
gochain-iconee  | 	/usr/local/go/src/runtime/asm_amd64.s:1571
gochain-iconee  | I|20231106-12:25:41.816847|b6b5|faddbb|chain|chain.go:542 Fail to start Consensus err=E2100:FAIL to deploy ChainScore
gochain-iconee  | P|20231106-12:25:41.816880|b6b5|-|main|main.go:530 FAIL to start Chain err=E2100:FAIL to deploy ChainScore
gochain-iconee  | github.com/icon-project/goloop/common/errors.Code.Wrapf
gochain-iconee  | 	/work/common/errors/errors.go:100
gochain-iconee  | github.com/icon-project/goloop/service/transaction.(*genesisV3).Execute
gochain-iconee  | 	/work/service/transaction/genesis_v3.go:275
gochain-iconee  | github.com/icon-project/goloop/service.(*transition).executeTxsSequential
gochain-iconee  | 	/work/service/transition_se.go:60
gochain-iconee  | github.com/icon-project/goloop/service.(*transition).executeTxs
gochain-iconee  | 	/work/service/transition.go:906
gochain-iconee  | github.com/icon-project/goloop/service.(*transition).doExecute
gochain-iconee  | 	/work/service/transition.go:760
gochain-iconee  | runtime.goexit
gochain-iconee  | 	/usr/local/go/src/runtime/asm_amd64.s:1571
gochain-iconee  | Wrapping E0005:RevisionIsHigherMax(19 > 9)
gochain-iconee  | github.com/icon-project/goloop/common/errors.Code.Errorf
gochain-iconee  | 	/work/common/errors/errors.go:92
gochain-iconee  | github.com/icon-project/goloop/service/platform/basic.(*ChainScore).Install
gochain-iconee  | 	/work/service/platform/basic/chainscore.go:632
gochain-iconee  | github.com/icon-project/goloop/service/contract.DeployAndInstallSystemSCORE
gochain-iconee  | 	/work/service/contract/contractmanager.go:108
gochain-iconee  | github.com/icon-project/goloop/service/transaction.(*genesisV3).Execute
gochain-iconee  | 	/work/service/transaction/genesis_v3.go:273
gochain-iconee  | github.com/icon-project/goloop/service.(*transition).executeTxsSequential
gochain-iconee  | 	/work/service/transition_se.go:60
gochain-iconee  | github.com/icon-project/goloop/service.(*transition).executeTxs
gochain-iconee  | 	/work/service/transition.go:906
gochain-iconee  | github.com/icon-project/goloop/service.(*transition).doExecute
gochain-iconee  | 	/work/service/transition.go:760
gochain-iconee  | runtime.goexit
gochain-iconee  | 	/usr/local/go/src/runtime/asm_amd64.s:1571
gochain-iconee  | I|20231106-12:25:41.816946|b6b5|-|TP|transport.go:235 acceptRoutine accept tcp4 0.0.0.0:8080: use of closed network connection sub=listener
gochain-iconee  | panic: (*logrus.Entry) 0xc000525730
gochain-iconee  | 
gochain-iconee  | goroutine 1 [running]:
gochain-iconee  | github.com/sirupsen/logrus.Entry.log({0xc000146070, 0xc0000c0cf0, {0x0, 0x0, 0x0}, 0x0, 0x0, {0x0, 0x0}, 0x0, ...}, ...)
gochain-iconee  | 	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:259 +0x2de
gochain-iconee  | github.com/sirupsen/logrus.(*Entry).Log(0xc00037e310, 0x0, {0xc0001b9540?, 0x1?, 0x1?})
gochain-iconee  | 	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:287 +0xa8
gochain-iconee  | github.com/sirupsen/logrus.(*Entry).Logf(0xc00037e310, 0x0, {0x15ba80a?, 0x10?}, {0xc00032f380?, 0x10?, 0xc000079000?})
gochain-iconee  | 	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:333 +0x85
gochain-iconee  | github.com/sirupsen/logrus.(*Entry).Panicf(0xc000460db0?, {0x15ba80a?, 0x8db227?}, {0xc00032f380?, 0x13e44c0?, 0x15a4301?})
gochain-iconee  | 	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:371 +0x34
gochain-iconee  | main.Execute(0xc0003ca000?, {0xc00030f560?, 0x12?, 0x13?})
gochain-iconee  | 	/work/cmd/gochain/main.go:530 +0x31f0
gochain-iconee  | github.com/spf13/cobra.(*Command).execute(0xc0003ca000, {0xc000032150, 0x12, 0x13})
gochain-iconee  | 	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
gochain-iconee  | github.com/spf13/cobra.(*Command).ExecuteC(0xc0003ca000)
gochain-iconee  | 	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bc
gochain-iconee  | github.com/spf13/cobra.(*Command).Execute(...)
gochain-iconee  | 	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
gochain-iconee  | main.main()
gochain-iconee  | 	/work/cmd/gochain/main.go:178 +0xffd
```

**Comment by sink772** [comment]
Did you check https://github.com/icon-project/gochain-local#requirements?

You need to build the image via `make gochain-icon-image`.

**Comment by robcxyz** [comment]
Yes, that is what I did.
